### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by missinglink** [sevko/batch-request-stream#1]
Heya, I've got some feedback if you're interested?

Looks very nice, and good use of eventemitters, especially using `this.once` to resume the flow.
#### model options as an object

I personally prefer to have the constructor options as an object rather than an array (type thing).

The advantage here is that you can see the name of the property you are setting and you can omit properties without having to specify them as null, much prettier ;)

``` javascript
var batchRequestStream = createBatchRequestStream(
    request,
    null, // default: 100
    null, // default: 100
    {objectMode: true} // if you need to write objects
);
```

vs.

``` javascript
var options = {
  request: request,
  streamOptions: {objectMode: true}
};
var batchRequestStream( options );
```
#### exclusively for request?

seems you could use this for other things too, is there any advantage in making it more general-purpose?
#### core streams module

``` javascript
var stream = require("stream");
```

As per our conversation, isn't it better to use: https://github.com/isaacs/readable-stream/blob/master/readable.js#L5 so you can support older versions of node?
#### `requestCompleted()` function deceleration not really needed?

you could probably do away with it completely if you did something like this instead:

``` javascript
request(batch, writeStream.emit.bind(writeStream,"requestCompleted"));
```

... but I do tent to over-use `bind()` ;)
#### code style

on this line https://github.com/sevko/batch-request-stream/blob/master/index.js#L70 I would make this a return statement, it's fine as it is but it's a nice way to signal that that code block is finished, easier to read.

**Comment by missinglink** [comment]
re: the tests, they are a bit fragile and I'm not sure if they're testing what you want them to?

eg: removing these 2 lines and the test still passes?

``` bash
peter@mini:/var/www/batch-request-stream$ d
diff --git a/test/test.js b/test/test.js
index c188431..157bb43 100644
--- a/test/test.js
+++ b/test/test.js
@@ -17,8 +17,8 @@ tap("Test batch-sizes.", function callback(test){
        var numItems = batchSize * 5;

        function request(batch, requestCompleted){
-               test.equal(batch.length, batchSize, "Batch size matches.");
-               requestCompleted();
+               // test.equal(batch.length, batchSize, "Batch size matches.");
+               // requestCompleted();
        }
```

an easy fix would be something like this:

``` bash
peter@mini:/var/www/batch-request-stream$ d
diff --git a/test/test.js b/test/test.js
index c188431..b713fde 100644
--- a/test/test.js
+++ b/test/test.js
@@ -16,6 +16,8 @@ tap("Test batch-sizes.", function callback(test){
        var batchSize = 4;
        var numItems = batchSize * 5;

+       test.plan( 5 );
+
        function request(batch, requestCompleted){
                test.equal(batch.length, batchSize, "Batch size matches.");
                requestCompleted();
@@ -27,7 +29,6 @@ tap("Test batch-sizes.", function callback(test){
        for(var num = 0; num < numItems; num++){
                batchRequestStream.write(num);
        }
-       test.end();
 });
```

It might be nice to have a test to ensure the final half-batch is executed on `finished`.

**Comment by sevko** [comment]
Thanks for the feedback! The following comments I agree with:
- configuration object instead of multiple arguments: good call, more idiomatic. d01c4e8.
- `readable-stream` vs `stream`: portability's a win. e7805d4
- `return` style: meant to refactor that part into a return so the `else{ next(); }` isn't repeated. d01c4e8

On the other hand:
- demoting `requestCompleted()` to a `.bind()`: both approaches are practically the same thing, since `.bind()` creates another function implicitly. An explicit `requestCompleted()` is more readable and self-documented, though.
- more general purpose: not sure I follow. This isn't exclusive to the `request` package, if that's what you're implying, and can be used with any asynchronous calls.

**Comment by sevko** [comment]
Additionally made the tests more strict (b4d839c).
